#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`
runApplication blockMesh
runApplication $application
postProcess -latestTime -field T
#paraview postProcessing/surfaceSampling/0.0001/T_palne.vtk
#------------------------------------------------------------------------------
